//
//  ProgressBarDraw.swift
//  ProgressBarFun
//
//  Created by Sivcan Singh on 26/11/16.
//  Copyright (c) 2016 GraphicDen Labs. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//



import UIKit

public class ProgressBarDraw : NSObject {

    //// Drawing Methods

    public class func drawProgressBar(frame frame: CGRect = CGRect(x: 0, y: 0, width: 300, height: 16), progress: CGFloat = 170) {
        //// Color Declarations
        let color = UIColor(red: 0.446, green: 1.000, blue: 0.000, alpha: 1.000)

        //// ProgressBorder Drawing
        let progressBorderPath = UIBezierPath(roundedRect: CGRect(x: frame.minX + 1, y: frame.minY + 1, width: floor((frame.width - 1) * 0.99666 + 0.5), height: 14), cornerRadius: 7)
        color.setStroke()
        progressBorderPath.lineWidth = 1
        progressBorderPath.stroke()


        //// ProgressActive Drawing
        let progressActivePath = UIBezierPath(roundedRect: CGRect(x: 1, y: 1, width: progress, height: 14), cornerRadius: 7)
        color.setFill()
        progressActivePath.fill()
    }

}
